import Head from "next/head";

import BaseContainerLayout from "../layouts/BaseContainerLayout";
import Hero from "../components/Hero";
import Experience from "../components/Experience";
import Education from "../components/Education";
import Skills from "../components/Skills";
import Services from "../components/Services";
import Projects from "../components/Projects";
import Awards from "../components/Awards";
import Interests from "../components/Interests";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gaurav Sharma - DevJunction</title>
        <meta name="description" content="Generated by DevJunction" />
      </Head>

      <BaseContainerLayout>
        <Hero />
        <hr className="m-0" />
        <Experience />
        <hr className="m-0" />
        <Education />
        <hr className="m-0" />
        <Skills />
        <hr className="m-0" />
        <Services />
        <hr className="m-0" />
        <Projects />
        <hr className="m-0" />
        <Awards />
        <hr className="m-0" />
        <Interests />
        <hr className="m-0" />
      </BaseContainerLayout>
    </>
  );
}
